### ISSUE TITLE
CraftTweaker .displayName function changes ALL block names that vary over meta

### ISSUE THREAD

**Issue by Vyraal1** [TehNut/Xtones#14]
Was using CraftTweaker and the zenscript line 

`<xtones:zome:12>.displayName = "Base Alchemical Beacon (Active)";`

to change the names of an xtone block. However it ended up changing all of the Zome blocks instead of just the red one of meta 12. displayName seems to work correctly with other items such as Thermal Foundation ingots, or wood planks.

**Comment by TehNut** [comment]
Yup

**Comment by InsomniaKitten** [comment]
`<xtones:zome>.withDamage(12).displayName = "Base Alchemical Beacon (Active)";`

https://crafttweaker.readthedocs.io/en/latest/#Vanilla/Items/Item_Conditions/

**Comment by Vyraal1** [comment]
Is it possible to make it so that blocks of different colors/metas have different names in xtones?

**Comment by TehNut** [comment]
Nope
