### ISSUE TITLE
Chisels & Bits can't chisel Glaxx blocks

### ISSUE THREAD

**Issue by natronium** [TehNut/Xtones#15]
I was going to submit a PR, using the IMC fix mentioned [here](https://github.com/AlgorithmX2/Chisels-and-Bits/issues/192#issuecomment-263771316) in the same vein as the Chisel compatibility code you've already got, but I'm not familiar with forge, and couldn't seem to get it working. Hardwiring [`BlockXtone#isFullBlock`](https://github.com/TehNut/Xtones/blob/1.12/src/main/java/tehnut/xtones/block/BlockXtone.java#L61) to *always* return `true` lets C&B recognize the blocks as modifiable, [since that's what it's actually checking](https://github.com/AlgorithmX2/Chisels-and-Bits/blob/1.12/src/main/java/mod/chiselsandbits/chiseledblock/BlockBitInfo.java#L208), but I'm not sure that that really counts as a solution...

**Comment by ChloeDawn** [comment]
Reopening until there is an actual release with this fix in it. Hopefully, it'll be available soon.

**Comment by ChloeDawn** [comment]
Fixed in [1.1.0](https://www.curseforge.com/minecraft/mc-mods/xtones/files/3025982)
