### ISSUE TITLE
VanillaFix picked up this odd issue

### ISSUE THREAD

**Issue by Sunconure11** [TehNut/Xtones#16]
https://paste.dimdev.org/dafoxaqadu.mccrash

Did not generate a crash, but it kept spamming my game with it encountering this issue.

**Comment by ChloeDawn** [comment]
Is this still a reproducible bug? The log file no longer exists at that URL so I cannot review it

**Comment by Sunconure11** [comment]
This was over two years ago. I don't think I even have the log in question anymore.
