### ISSUE TITLE
Chisels & Bits can't chisel Glaxx blocks [Xtones]

### ISSUE THREAD

**Issue by Electro2903** [TehNut/Xtones#19]
As the title says, I am having trouble cutting The "Glaxx" blocks from Xtones. I have tried with the different chisels and bits tools, and also forge microblocks. None of them worked. Does anyone know how I can cut them?

I know that it is possible with chisels and bits and Ztones glass, but I am playing on 1.12.2. (Xtones is for higher versions)

**Comment by ChloeDawn** [comment]
Duplicate of https://github.com/TehNut/Xtones/issues/15, there will hopefully be a new release soon
