### ISSUE TITLE
[1.10.2] Lack of "type number" in WAILA/TOP and ordering off.

### ISSUE THREAD

**Issue by DeadSix27** [TehNut/Xtones#2]
This was done by translations prior to 1.10.2.

```
....
tile.zythBlock. (0).name=Zyth ⓪
tile.zythBlock. (1).name=Zyth ①
tile.zythBlock. (2).name=Zyth ②
....
```
Which made the name and number appear on the tool tips (very helpful).

Also the ordering currently is off as it starts counting from 1 and not 0. The original ztones started of 0.

![image](https://cloud.githubusercontent.com/assets/1492505/22174199/e0749eb6-dfd8-11e6-94ed-d54d4cb3ce04.png)

**Comment by TehNut** [comment]
Copying over from PR: The off by one was intentional as most users don't have a development background and find starting at 0 odd

I will add the number to the Waila tooltip though.
