### ISSUE TITLE
Azur cannot be crafted with any blue dye

### ISSUE THREAD

**Issue by faraday326** [TehNut/Xtones#20]
I am currently playing FTB:I (2.0.5) which has xtones version 1.12-1.0.8-11.

It seems like the recipe for the Azur block should be w/ any blue dye (based on all the other similar blocks that use dyes) but this one seems to require lapis lazuli.

**Comment by faraday326** [comment]
awesome! thank you.

**Comment by ChloeDawn** [comment]
Fixed in [1.1.0](https://www.curseforge.com/minecraft/mc-mods/xtones/files/3025982)
