### ISSUE TITLE
[Bug] Xtones 1.2.0 chiselMode 1 not working

### ISSUE THREAD

**Issue by drakray** [TehNut/Xtones#22]
Selecting mode 1 show variant X of every style in JEI and Chisel, instead of every variant of style X

MC 1.12.2
Forge 2847
Xtones 1.2.0
Chisel 1.0.2.45
BunchaOthers

**Comment by ChloeDawn** [comment]
Fixed in [1.2.1](https://www.curseforge.com/minecraft/mc-mods/xtones/files/3059121)

**Comment by drakray** [comment]
Work like a charm thanks!! :)
