### ISSUE TITLE
Unable to read property

### ISSUE THREAD

**Issue by Breadabix** [TehNut/Xtones#23]
Im playing with the latest version of xtones for 1.12 and my game output is being spammed with
"Unable to read property: variant with value: sixteen for blockstate: {Properties:{variant:"sixteen"},Name:"xtones:zane"}"

I have not been able to find the reason for this.

**Comment by ChloeDawn** [comment]
I changed the way the blockstates were implemented without considering existing resource packs.
I will revert this change to fix the incompatibility.

**Comment by ChloeDawn** [comment]
Fixed in [1.2.2](https://www.curseforge.com/minecraft/mc-mods/xtones/files/3248033)
