### ISSUE TITLE
BrokenCraftingRecipeException (JEI or XTones issue?)

### ISSUE THREAD

**Issue by DeadSix27** [TehNut/Xtones#4]
Versions:
`jei_1.10.2-3.14.7.415.jar`
`Xtones-1.10.2-1.0.0-2.jar`

I posted this issue on both trackers as I do not know which one of the mods is responsible.

Other Issue link: https://github.com/mezz/JustEnoughItems/issues/752

Stacktrace: http://pastebin.com/pmbUuhNk

**Comment by ChloeDawn** [comment]
"This page has been removed!" rip stacktrace @DeadSix27

**Comment by DeadSix27** [comment]
@InsomniaKitten lol wut, should stop using pastebin and use my own paste clone.. but im too busy to set that up and posting stacktraces in github is spammy.. 
Here is the new one: https://paste.ubuntu.com/24078914/

**Comment by TehNut** [comment]
Hm. Apparently JEI thinks the center item  (whatever random vanilla item it is) is null. I'll have to look into it a bit. Nothing from Vanilla should be null at point.

**Comment by TehNut** [comment]
Well that's embarrassing.
