### ISSUE TITLE
Creative inventory tabs not right

### ISSUE THREAD

**Issue by Zygus42** [TehNut/Xtones#6]
Xtones-1.12-1.0.2-4
forge-1.12-14.21.0.2322-installer-win

All of the inventory tabs in Creative mode have all of the Xtones items and blocks listed in them, including all the vanilla tabs and all the mod tabs.

BoP had the same issue until today, but they just fixed it.

**Comment by TehNut** [comment]
Oh, that's an *interesting* change to how Creative tabs are handled. Thanks Mojang.

**Comment by Zygus42** [comment]
lol :)  Guessing it won't be the last time I'm reporting this issue :)
